Replaced with the new context selector
Tendrl/ui pull request #1069
Opened 2018-09-17 07:15 UTC by gnehapk

Bugzilla: 1629520
tendrl-github-id: https://github.com/Tendrl/ui/issues/1065

2018-09-17 07:16 UTC, gnehapk commented
Screenshots - 

<img width="1680" alt="screenshot1" src="https://user-images.githubusercontent.com/5517376/45609909-eeda2500-ba94-11e8-814c-7b873659cbab.png">
<img width="1678" alt="screenshot2" src="https://user-images.githubusercontent.com/5517376/45609910-eeda2500-ba94-11e8-803a-2aa99de84d1b.png">
<img width="1680" alt="screenshot3" src="https://user-images.githubusercontent.com/5517376/45609912-ef72bb80-ba94-11e8-8c95-76120fb93414.png">

2018-09-18 08:41 UTC, a2batic requested changes
The context switcher works fine, but it seems it is not responsive.

2018-09-18 08:42 UTC, a2batic commented
@gnehapk attached screenshot

![screenshot from 2018-09-18 14-01-42](https://user-images.githubusercontent.com/12200504/45675339-cc0b4780-bb4c-11e8-94ec-bceb5a4022d4.png)

2018-09-19 05:22 UTC, a2batic approved these changes

2018-09-19 07:06 UTC, merged