Add "make snapshot" target for building packages from develop branch
Tendrl/ui pull request #485
Opened 2017-07-04 12:59 UTC by TimothyAsirJeyasing

tendrl-bug-id: Tendrl/dashboard#442
Signed-off-by: Timothy Asir J <tjeyasin@redhat.com>

2017-07-04 13:00 UTC, TimothyAsirJeyasing commented
@r0h4n , @nthomas-redhat , @shtripat , @dahorak , Please review

2017-07-04 13:17 UTC, TimothyAsir commented
@mbukatov Please review

2017-07-11 08:28 UTC, dahorak requested changes

2017-07-11 08:28 UTC, dahorak commented on Makefile
> +	  -e "/^Release:/cRelease: $(shell date +"%m_%d_%Y_%H_%M_%S")"
Please see this comment related to the version format: https://github.com/Tendrl/api/issues/209#issuecomment-314371093.

2017-07-13 10:04 UTC, TimothyAsir commented on Makefile
> +	  -e "/^Release:/cRelease: $(shell date +"%m_%d_%Y_%H_%M_%S")"
So, do you mean we need some thing like this:
("%Y_%m_%d_%H_%M_%S").$(SHORTCOMMIT)

Are you ok with shortcommit at the end of the release version?

2017-07-13 10:08 UTC, TimothyAsir commented
@mbukatov please review

2017-07-14 08:54 UTC, mbukatov commented on Makefile
> +	  -e "/^Release:/cRelease: $(shell date +"%m_%d_%Y_%H_%M_%S")"
I would suggest this format: `("%Y%m%dT%H%M%S").$(SHORTCOMMIT)`

2017-07-19 06:18 UTC, TimothyAsir commented
@r0h4n , @ktdreyer , @mbukatov , @dahorak , Please review

2017-07-19 06:27 UTC, r0h4n commented
Please send this PR on "master" branch

2017-07-19 06:27 UTC, closed without merging