volume profile changes
Tendrl/ui pull request #838
Opened 2018-02-26 09:29 UTC by gnehapk

tendrl-github-issues:
- #819 
- #788 
- #769 
- #821

2018-02-26 09:31 UTC, r0h4n approved these changes

2018-02-26 09:55 UTC, a2batic approved these changes

2018-02-26 10:07 UTC, cybernth approved these changes

2018-02-26 10:24 UTC, cloudbehl requested changes
Please make the required changes.

2018-02-26 10:24 UTC, cloudbehl commented on src/modules/clusters/import-cluster/import-cluster.html
> +                    <input type="radio" name="enable" value="enable" id="enable" ng-model="vm.enableProfiling" checked>
If using the name property. The name property for all the input should be same as it denotes the group of a radio button.

2018-02-26 10:24 UTC, cloudbehl commented on src/commons/factories/volume-factory.js
> +        vm.enableProfiling = function(volume, clusterId) {
We should make the functions generic to stop code repetition. Enable and disable profiling is having just a parameter change. so please make a generic function.

2018-02-26 10:24 UTC, cloudbehl commented on src/commons/stores/cluster-store.js
> +            function _getProfileStatus(status) {
Cleaner way to write:

profileState[volume_profiling_state]

var profileState = {"enable": "Enabled",
"disabled": "Disabled",
"mixed": "Mixed"}

2018-02-26 10:24 UTC, cloudbehl commented on src/commons/stores/volume-store.js
> +        store.enableProfiling = function(volume, clusterId) {
create a generic function for enabling and disable profiling.

2018-02-26 10:24 UTC, cloudbehl commented on src/modules/tasks/global-task-detail/global-task-detail.js
> +                vm.clusterObj = clusterStore.getClusterDetails(vm.clusterId);
create a different function for the same set of lines and call a function.

basically, the below lines should in function and call the function from if and else both. will look much cleaner

+                        vm.clusterObj = clusterStore.getClusterDetails(vm.clusterId);
+                        vm.clusterName = vm.clusterObj.cluster_id || "NA";
+                        vm.clusterStatus = clusterStore.checkStatus(vm.clusterObj);
+
+                        taskStore.getJobDetail($stateParams.taskId)
+                            .then(function(data) {
+                                vm.taskDetail = data;
+                                vm.isDataLoading = false;
+
+                                _getTaskLogs();
+                                startStatusTimer();
+                                startMessageTimer();
+                            });

2018-02-26 10:24 UTC, cloudbehl commented on src/modules/volumes/volume-list/volume-list.html
> +                    <button ng-show="volume.profileStatus === 'Enabled' || (volume.currentTask.job_name === 'StopProfiling' && volume.currentTask.status === 'in_progress')" class="btn btn-default das
please return True and false to the ng-show by calling a function.

2018-02-26 10:24 UTC, cloudbehl commented on src/modules/volumes/volume-list/volume-list.js
> +            volumeStore.disableProfiling(volume, vm.clusterId)
same as above,

create a single and generic function for both enable and disable

2018-02-26 10:24 UTC, cloudbehl commented on src/modules/volumes/volume-list/volume-list.js
> +            var compValue = 0;
can avoid If else by doing the below.

var sortId = vm.sortConfig.currentField.id;
compValue = item1["sortId"].localeCompare(item2[sortId]);

2018-02-26 13:22 UTC, a2batic commented on src/modules/volumes/volume-list/volume-list.js
> +            var compValue = 0;
@cloudbehl, but wont this function loose its consistency when compared to other views ?

2018-02-26 14:32 UTC, cloudbehl commented on src/modules/volumes/volume-list/volume-list.js
> +            var compValue = 0;
@a2batic Take it as a refactoring for other views. If it improves this we can work with other views and maintain that consistency

2018-02-27 08:46 UTC, cloudbehl approved these changes
LGTM

2018-02-27 09:14 UTC, merged