cluster name changes
Tendrl/ui pull request #910
Opened 2018-04-05 09:22 UTC by gnehapk

tendrl-github-id: https://github.com/Tendrl/ui/issues/656

Signed-off-by: Neha Gupta <gnehapk@gmail.com>

2018-04-06 05:45 UTC, a2batic approved these changes

2018-04-06 06:45 UTC, cloudbehl approved these changes

2018-04-12 13:46 UTC, cloudbehl commented
@gnehapk This requires changes to the creation of the link of tendrl-ui to grafana. Pass cluster_name instead of cluster_id.

2018-04-12 13:47 UTC, cloudbehl requested changes
@gnehapk This requires changes to the creation of the link of tendrl-ui to grafana. Pass cluster_name instead of cluster_id.

2018-04-13 12:17 UTC, closed without merging