[WIP] Fixed filter for volume's brick detail view
Tendrl/ui pull request #965
Opened 2018-05-20 12:41 UTC by gnehapk

Bugzilla - 1577938
tendrl-bug-id - https://github.com/Tendrl/ui/issues/964

Signed-off-by: Neha Gupta <gnehapk@gmail.com>

2018-05-21 09:21 UTC, a2batic commented on src/modules/bricks/volume-bricks/volume-bricks.js
> +                    return -9999;
@gnehapk, we can directly return subVol here, we need not check it

2018-05-21 09:23 UTC, gnehapk commented on src/modules/bricks/volume-bricks/volume-bricks.js
> +                    return -9999;
@a2batic agreed.

2018-05-22 02:45 UTC, r0h4n commented
@nthomas-redhat @gnehapk 

Every UI PR needs to be reviewed and approved by @cloudbehl  as well. 

@cloudbehl  please review

2018-05-22 09:33 UTC, cloudbehl approved these changes
Looks good to me!

2018-05-22 09:40 UTC, a2batic submitted a review, later dismissed

2018-05-22 09:55 UTC, cloudbehl commented on src/modules/bricks/volume-bricks/volume-bricks.js
> +                list = JSON.parse(JSON.stringify(vm.subVolumeList));;
I just saw there are two semi-colon on this line, can you correct it

2018-05-22 09:58 UTC, cloudbehl requested changes
can you fix the https://app.codacy.com/app/openstack/ui/pullRequest?prid=1671267 error whatever is possible?

2018-05-22 09:59 UTC, cybernth submitted a review, later dismissed

2018-05-22 10:21 UTC, a2batic approved these changes

2018-05-22 10:24 UTC, cloudbehl approved these changes

2018-05-22 10:33 UTC, cybernth approved these changes

2018-05-22 10:34 UTC, merged